#pragma once
#include <stdint.h>
#include "kwrappers/kui_types.h"

#ifdef __cplusplus
extern "C"
{
#endif

/* ===== Named colors (CSS set) ===== */
#ifndef KGFX_COLOR_PACK
#define KGFX_COLOR_PACK 1

/* helpers */
#ifdef __cplusplus
#define KCOLOR_RGB(r, g, b) \
    kcolor { (uint8_t)(r), (uint8_t)(g), (uint8_t)(b) }
#else
#define KCOLOR_RGB(r, g, b) ((kcolor){(uint8_t)(r), (uint8_t)(g), (uint8_t)(b)})
#endif

#define KCOLOR_HEX(h) KCOLOR_RGB(((h) >> 16) & 0xFF, ((h) >> 8) & 0xFF, (h) & 0xFF)

/* basics */
#define black KCOLOR_RGB(0, 0, 0)
#define white KCOLOR_RGB(255, 255, 255)
#define red KCOLOR_RGB(255, 0, 0)
#define green KCOLOR_RGB(0, 255, 0)
#define blue KCOLOR_RGB(0, 0, 255)
#define cyan KCOLOR_RGB(0, 255, 255)
#define magenta KCOLOR_RGB(255, 0, 255)
#define yellow KCOLOR_RGB(255, 255, 0)
#define gray KCOLOR_RGB(128, 128, 128)
#define grey gray
#define silver KCOLOR_HEX(0xC0C0C0)
#define maroon KCOLOR_HEX(0x800000)
#define olive KCOLOR_HEX(0x808000)
#define purple KCOLOR_HEX(0x800080)
#define teal KCOLOR_HEX(0x008080)
#define navy KCOLOR_HEX(0x000080)
#define fuchsia KCOLOR_HEX(0xFF00FF)
#define aqua KCOLOR_HEX(0x00FFFF)

/* full CSS set (lower_snake_case) */
#define aliceblue KCOLOR_HEX(0xF0F8FF)
#define antiquewhite KCOLOR_HEX(0xFAEBD7)
#define aquamarine KCOLOR_HEX(0x7FFFD4)
#define azure KCOLOR_HEX(0xF0FFFF)
#define beige KCOLOR_HEX(0xF5F5DC)
#define bisque KCOLOR_HEX(0xFFE4C4)
#define blanchedalmond KCOLOR_HEX(0xFFEBCD)
#define blueviolet KCOLOR_HEX(0x8A2BE2)
#define brown KCOLOR_HEX(0xA52A2A)
#define burlywood KCOLOR_HEX(0xDEB887)
#define cadet_blue KCOLOR_HEX(0x5F9EA0)
#define chartreuse KCOLOR_HEX(0x7FFF00)
#define chocolate KCOLOR_HEX(0xD2691E)
#define coral KCOLOR_HEX(0xFF7F50)
#define cornflower_blue KCOLOR_HEX(0x6495ED)
#define cornsilk KCOLOR_HEX(0xFFF8DC)
#define crimson KCOLOR_HEX(0xDC143C)
#define dark_blue KCOLOR_HEX(0x00008B)
#define dark_cyan KCOLOR_HEX(0x008B8B)
#define dark_goldenrod KCOLOR_HEX(0xB8860B)
#define dark_gray KCOLOR_HEX(0xA9A9A9)
#define dark_grey KCOLOR_HEX(0xA9A9A9)
#define dark_green KCOLOR_HEX(0x006400)
#define dark_khaki KCOLOR_HEX(0xBDB76B)
#define dark_magenta KCOLOR_HEX(0x8B008B)
#define dark_olive_green KCOLOR_HEX(0x556B2F)
#define dark_orange KCOLOR_HEX(0xFF8C00)
#define dark_orchid KCOLOR_HEX(0x9932CC)
#define dark_red KCOLOR_HEX(0x8B0000)
#define dark_salmon KCOLOR_HEX(0xE9967A)
#define dark_sea_green KCOLOR_HEX(0x8FBC8F)
#define dark_slate_blue KCOLOR_HEX(0x483D8B)
#define dark_slate_gray KCOLOR_HEX(0x2F4F4F)
#define dark_slate_grey KCOLOR_HEX(0x2F4F4F)
#define dark_turquoise KCOLOR_HEX(0x00CED1)
#define dark_violet KCOLOR_HEX(0x9400D3)
#define deep_pink KCOLOR_HEX(0xFF1493)
#define deep_sky_blue KCOLOR_HEX(0x00BFFF)
#define dim_gray KCOLOR_HEX(0x696969)
#define dim_grey KCOLOR_HEX(0x696969)
#define dodger_blue KCOLOR_HEX(0x1E90FF)
#define firebrick KCOLOR_HEX(0xB22222)
#define floral_white KCOLOR_HEX(0xFFFAF0)
#define forest_green KCOLOR_HEX(0x228B22)
#define gainsboro KCOLOR_HEX(0xDCDCDC)
#define ghost_white KCOLOR_HEX(0xF8F8FF)
#define gold KCOLOR_HEX(0xFFD700)
#define goldenrod KCOLOR_HEX(0xDAA520)
#define green_yellow KCOLOR_HEX(0xADFF2F)
#define honeydew KCOLOR_HEX(0xF0FFF0)
#define hot_pink KCOLOR_HEX(0xFF69B4)
#define indian_red KCOLOR_HEX(0xCD5C5C)
#define indigo KCOLOR_HEX(0x4B0082)
#define ivory KCOLOR_HEX(0xFFFFF0)
#define khaki KCOLOR_HEX(0xF0E68C)
#define lavender KCOLOR_HEX(0xE6E6FA)
#define lavender_blush KCOLOR_HEX(0xFFF0F5)
#define lawn_green KCOLOR_HEX(0x7CFC00)
#define lemon_chiffon KCOLOR_HEX(0xFFFACD)
#define light_blue KCOLOR_HEX(0xADD8E6)
#define light_coral KCOLOR_HEX(0xF08080)
#define light_cyan KCOLOR_HEX(0xE0FFFF)
#define light_goldenrod_yellow KCOLOR_HEX(0xFAFAD2)
#define light_gray KCOLOR_HEX(0xD3D3D3)
#define light_grey KCOLOR_HEX(0xD3D3D3)
#define light_green KCOLOR_HEX(0x90EE90)
#define light_pink KCOLOR_HEX(0xFFB6C1)
#define light_salmon KCOLOR_HEX(0xFFA07A)
#define light_sea_green KCOLOR_HEX(0x20B2AA)
#define light_sky_blue KCOLOR_HEX(0x87CEFA)
#define light_slate_gray KCOLOR_HEX(0x778899)
#define light_slate_grey KCOLOR_HEX(0x778899)
#define light_steel_blue KCOLOR_HEX(0xB0C4DE)
#define light_yellow KCOLOR_HEX(0xFFFFE0)
#define lime KCOLOR_HEX(0x00FF00)
#define lime_green KCOLOR_HEX(0x32CD32)
#define linen KCOLOR_HEX(0xFAF0E6)
#define medium_aquamarine KCOLOR_HEX(0x66CDAA)
#define medium_blue KCOLOR_HEX(0x0000CD)
#define medium_orchid KCOLOR_HEX(0xBA55D3)
#define medium_purple KCOLOR_HEX(0x9370DB)
#define medium_sea_green KCOLOR_HEX(0x3CB371)
#define medium_slate_blue KCOLOR_HEX(0x7B68EE)
#define medium_spring_green KCOLOR_HEX(0x00FA9A)
#define medium_turquoise KCOLOR_HEX(0x48D1CC)
#define medium_violet_red KCOLOR_HEX(0xC71585)
#define midnight_blue KCOLOR_HEX(0x191970)
#define mint_cream KCOLOR_HEX(0xF5FFFA)
#define misty_rose KCOLOR_HEX(0xFFE4E1)
#define moccasin KCOLOR_HEX(0xFFE4B5)
#define navajo_white KCOLOR_HEX(0xFFDEAD)
#define old_lace KCOLOR_HEX(0xFDF5E6)
#define olive_drab KCOLOR_HEX(0x6B8E23)
#define orange KCOLOR_HEX(0xFFA500)
#define orange_red KCOLOR_HEX(0xFF4500)
#define orchid KCOLOR_HEX(0xDA70D6)
#define pale_goldenrod KCOLOR_HEX(0xEEE8AA)
#define pale_green KCOLOR_HEX(0x98FB98)
#define pale_turquoise KCOLOR_HEX(0xAFEEEE)
#define pale_violet_red KCOLOR_HEX(0xDB7093)
#define papaya_whip KCOLOR_HEX(0xFFEFD5)
#define peach_puff KCOLOR_HEX(0xFFDAB9)
#define peru KCOLOR_HEX(0xCD853F)
#define pink KCOLOR_HEX(0xFFC0CB)
#define plum KCOLOR_HEX(0xDDA0DD)
#define powder_blue KCOLOR_HEX(0xB0E0E6)
#define rosy_brown KCOLOR_HEX(0xBC8F8F)
#define royal_blue KCOLOR_HEX(0x4169E1)
#define saddle_brown KCOLOR_HEX(0x8B4513)
#define salmon KCOLOR_HEX(0xFA8072)
#define sandy_brown KCOLOR_HEX(0xF4A460)
#define sea_green KCOLOR_HEX(0x2E8B57)
#define seashell KCOLOR_HEX(0xFFF5EE)
#define sienna KCOLOR_HEX(0xA0522D)
#define sky_blue KCOLOR_HEX(0x87CEEB)
#define slate_blue KCOLOR_HEX(0x6A5ACD)
#define slate_gray KCOLOR_HEX(0x708090)
#define slate_grey KCOLOR_HEX(0x708090)
#define snow KCOLOR_HEX(0xFFFAFA)
#define spring_green KCOLOR_HEX(0x00FF7F)
#define steel_blue KCOLOR_HEX(0x4682B4)
#define tan KCOLOR_HEX(0xD2B48C)
#define thistle KCOLOR_HEX(0xD8BFD8)
#define tomato KCOLOR_HEX(0xFF6347)
#define turquoise KCOLOR_HEX(0x40E0D0)
#define violet KCOLOR_HEX(0xEE82EE)
#define wheat KCOLOR_HEX(0xF5DEB3)
#define white_smoke KCOLOR_HEX(0xF5F5F5)
#define yellow_green KCOLOR_HEX(0x9ACD32)

#endif /* KGFX_COLOR_PACK */

#ifdef __cplusplus
}
#endif