param(
  [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..\..\..")).Path,
  [ValidateSet("Release","Debug")][string]$Config = "Release",
  [switch]$BuildX64
)

$netsurfRoot = Join-Path $ProjectRoot "third_party\netsurf-all-3.11"
if (!(Test-Path -LiteralPath $netsurfRoot)) {
  throw "NetSurf 3.11 sources are missing from third_party\netsurf-all-3.11"
}

function Get-CSourceTree([string]$RelativeRoot) {
  Get-ChildItem -LiteralPath (Join-Path $netsurfRoot $RelativeRoot) -Recurse -File -Filter *.c |
    ForEach-Object { $_.FullName }
}

# NetSurf's parser and layout libraries are built directly into the SACX image.
# The platform front ends and optional POSIX-backed handlers are deliberately
# omitted; Dihscover supplies those operations in netsurf_backend/fetch.cpp.
$netsurfLibraries = @()
foreach ($tree in @(
  "libparserutils\src", "libwapcaplet\src", "libhubbub\src", "libdom\src",
  "libcss\src", "libnsutils\src", "libnsbmp\src", "libnsgif\src"
)) { $netsurfLibraries += Get-CSourceTree $tree }
$netsurfLibraries = $netsurfLibraries | Where-Object {
  $_ -notmatch 'autogenerated-element-type\.c$' -and
  $_ -notmatch 'css_property_parser_gen\.c$'
}

$netsurfCore = @()
foreach ($tree in @("netsurf\content", "netsurf\desktop", "netsurf\utils")) {
  $netsurfCore += Get-CSourceTree $tree
}
$netsurfCore = $netsurfCore | Where-Object {
  $_ -notmatch '[\\/]test[\\/]' -and
  $_ -notmatch 'content[\\/]fetchers[\\/]curl\.c$' -and
  $_ -notmatch 'content[\\/]fetchers[\\/]file[\\/]' -and
  $_ -notmatch 'content[\\/]fs_backing_store\.c$' -and
  $_ -notmatch 'content[\\/]handlers[\\/]javascript[\\/]' -and
  $_ -notmatch 'content[\\/]handlers[\\/]image[\\/](jpeg|jpegxl|png|webp|jxl|nssprite|rsvg|rsvg246|svg|video)\.c$' -and
  $_ -notmatch 'desktop[\\/](save_pdf|print)\.c$'
}

$sources = @(
  "sdk\sacx\apps\dihscover\main.cpp",
  "sdk\sacx\apps\dihscover\netsurf_backend.cpp",
  "sdk\sacx\apps\dihscover\netsurf_fetch.cpp",
  "sdk\sacx\apps\dihscover\netsurf_dihos_image.c",
  "sdk\sacx\apps\dihscover\netsurf_libc.cpp",
  "sdk\sacx\apps\dihscover\netsurf_optional_stubs.c",
  "sdk\sacx\apps\dihscover\runtime.cpp",
  "sdk\sacx\apps\dihscover\heap.cpp",
  "third_party\tlsf\tlsf.c"
) + @(
  "third_party\netsurf-all-3.11\netsurf\content\handlers\javascript\none\none.c"
) + $netsurfLibraries + $netsurfCore

$args = @{
  ProjectRoot = $ProjectRoot
  Source = $sources
  OutSacx = "build\sacx\Dihscover.sacx"
  OutElfAA64 = "build\sacx\Dihscover_aa64.elf"
  OutElfX64 = "build\sacx\Dihscover_x64.elf"
  Imports = "sdk\sacx\imports\default.imports.txt"
  Config = $Config
  IncludeDir = @(
    "sdk\sacx\freestanding\include", "third_party\tlsf",
    "third_party\netsurf-all-3.11\netsurf",
    "third_party\netsurf-all-3.11\netsurf\include",
    "third_party\netsurf-all-3.11\netsurf\content\handlers",
    "third_party\netsurf-all-3.11\netsurf\content\fetchers\about",
    "third_party\netsurf-all-3.11\libparserutils\include",
    "third_party\netsurf-all-3.11\libparserutils\src",
    "third_party\netsurf-all-3.11\libwapcaplet\include",
    "third_party\netsurf-all-3.11\libwapcaplet\src",
    "third_party\netsurf-all-3.11\libhubbub\include",
    "third_party\netsurf-all-3.11\libhubbub\src",
    "third_party\netsurf-all-3.11\libdom\include",
    "third_party\netsurf-all-3.11\libdom\src",
    "third_party\netsurf-all-3.11\libcss\include",
    "third_party\netsurf-all-3.11\libcss\src",
    "third_party\netsurf-all-3.11\libnsutils\include",
    "third_party\netsurf-all-3.11\libnslog\include",
    "third_party\netsurf-all-3.11\libnsbmp\include",
    "third_party\netsurf-all-3.11\libnsgif\include"
  )
  Define = @(
    "NDEBUG", "DIHSCOVER_FREESTANDING", "netsurf", "nsdihos",
    "WITHOUT_ICONV_FILTER",
    "_ALIGNED=", "STMTEXPR=1",
    'NETSURF_BUILTIN_LOG_FILTER=\"level:WARNING\"',
    'NETSURF_BUILTIN_VERBOSE_FILTER=\"level:DEBUG\"',
    "NETSURF_USE_CURL=NO", "NETSURF_USE_DUKTAPE=NO",
    "NETSURF_USE_OPENSSL=NO", "NETSURF_USE_LIBICONV_PLUG=NO",
    "NETSURF_USE_VIDEO=NO", "NETSURF_USE_PNG=NO", "NETSURF_USE_WEBP=NO",
    "WITH_BMP", "WITH_GIF"
  )
}
if ($BuildX64) { $args.BuildX64 = $true }

& (Join-Path $ProjectRoot "build_sacx_app.ps1") @args
if ($LASTEXITCODE) { throw "Dihscover SACX build failed" }
